### ISSUE TITLE
Submission 1: Number bases and binary search

### ISSUE THREAD

**Issue by Sukhrobjon** [TannerYork/CS-1.3-Core-Data-Structures#1]
1. Number bases:
Your code looks clean, but you should check if test cases are passing. your functions return lowercase letters if the number is greater than base 10, So make sure when you are encoding or converting the number save the letter numbers in upper case so it passes test cases.
2. Binary search:
You need to add comments to your binary search function. it looks too complex to follow and you used one-liners there. E.g: this line
```
if type(array[index]) != tuple:
        return binary_search_recursive(list(enumerate(array)), item)
```
Talk to me during office hours or compare your code to your peers and see what you can simplify.

**Comment by TannerYork** [comment]
Thanks for the review, I updated the number bases to use lowercase so the test will pass and I changed the complex parts of the binary search to, hopefully, be more readable.
