### ISSUE TITLE
Submission 2: Palindrome and String Algorithms

### ISSUE THREAD

**Issue by Sukhrobjon** [TannerYork/CS-1.3-Core-Data-Structures#2]
1. Palindrome: 
It looks good, you could improve the code by making a helper function called `clean_text()` or something and clean the text: remove special chars, space, and lowercase the letters. Right now you are using too much unnecessary if clauses in your code. yes, it works but you make your code a lot simpler and easy to follow. for example these line:
```
if text[left_index] not in BASE_CHARACTERS:
            left_index += 1
elif text[right_index] not in BASE_CHARACTERS:
            right_index -= 1
```
2. String Algorithm:
Great work, you reused your code and wrote DRY code. You annotated the runtime accurately.

**Comment by TannerYork** [comment]
Thanks for the advice, I created the clean_text helper function and it reduced the amount of complexity needed for the algorithm.
