### ISSUE TITLE
Submission 3: Linked List, Stacks & Queue

### ISSUE THREAD

**Issue by Sukhrobjon** [TannerYork/CS-1.3-Core-Data-Structures#3]
1. Linked List - (Passes all tests)
- Since you now have `.size` the property you don't have to traverse the LinkedList anymore, just use
`return self.size`.
- In your `get_at_index(self, index)` function, since you know the index, which helps you to iterate the linked list until that specific point. 
So you can just use `for loop` instead of `while loop`
- In general, it is better to use `for loop` when you know the range(how many iterations you need to make), in this case, the index is given, on the other hand, you use `while loop` when you don't the how many iterations you need to make. 

2. Stacks - (Passes all tests)
- LinkedStack implementation has to use the head of the LinkedList to be considered efficient. because when you try to pop the head node from the stack it is O(1) run time, on the other hand, you are using the tail as the top of the stack so you pop() function runs O(n). 
You can change your push() function from using `self.list.append(item)` to `self.list.prepend(item)`

3. Queues - (Passes all tests)
- Looks like you are making the process a little complex in `dequeue()` function, instead of using the `get_index_at()` you can simply get the `head.data`.
```
item = self.list.get_at_index(0)
self.list.delete(self.list.head.data)
return item
```
so it would look like this:
```
item = self.list.head.data
self.list.delete(item)
return item
```

**Comment by TannerYork** [comment]
Thanks for the feedback, I fixed the issues in the data structures you mentioned.
