### ISSUE TITLE
Submission 4: Hash Tables and article draft

### ISSUE THREAD

**Issue by Sukhrobjon** [TannerYork/CS-1.3-Core-Data-Structures#4]
1. Hash Table - (Passes all tests)
- I think you don't need to use a counter in `length()` function because you already have .size property you can just call and avoid `for loop` to count the number of items in the hashtable.
2. Article 
- Great read, you can make your sample code even look better if you create `GitHub gist` and use an embedded link on medium, it looks much better.

**Comment by TannerYork** [comment]
Thanks for the feedback, I've fixed the hashtable code and update my article to use gist.
