### ISSUE TITLE
Submission 5: Trees and Tree traversal

### ISSUE THREAD

**Issue by Sukhrobjon** [TannerYork/CS-1.3-Core-Data-Structures#5]
1. Binary Tree Node
- you can change this in `height` function of BinaryTreeNode line `34-45`, here you are checking if right and left children are both are none at the same time, where else you did the same check?  
```
if self.right is None and self.left is None:
       return right_count if right_count > left_count else left_count
```
you can just check `if self.is_leaf()` instead of the line `34`.
2. Binary Search Tree
- Good work!
3. Tree Traversal
- Everything looks good, you have all (DFS) traversals are implemented recursively, try to do them iteratively.

**Comment by TannerYork** [comment]
Thanks for the feedback, I updated the height function to use the .is_leaf() method and the iterative DFS traversals are in too.
